import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
    state: {
        fireData: [{
                index: 1,
                altitude: 102.266683,
                latitude: 27.826986,
                level: "Special Major Accidents",
                fmen: 70,
                reason: "Solid material fires",
            },
            {
                index: 2,
                altitude: 102.311487,
                latitude: 27.797682,
                level: "Major Accidents",
                fmen: 55,
                reason: "Liquid substance fire",
            },

            {
                index: 3,
                altitude: 102.365732,
                latitude: 27.818939,
                level: "Larger accidents",
                fmen: 35,
                reason: "Gas fires",
            },
            {
                index: 4,
                altitude: 102.553529,
                latitude: 27.948594,
                level: "General Accidents",
                fmen: 20,
                reason: "Metal fires",
            },
            {
                index: 5,
                altitude: 102.402112,
                latitude: 28.320241,
                level: "General Accidents",
                fmen: 18,
                reason: "Live fires",
            },
            {
                index: 6,
                altitude: 103.604294,
                latitude: 28.278774,
                level: "Major Accidents",
                fmen: 30,
                reason: "Gas fires",
            },
            {
                index: 7,
                altitude: 100.598953,
                latitude: 28.289165,
                level: "Larger accidents",
                fmen: 39,
                reason: "Live fires",
            },
            {
                index: 8,
                altitude: 100.757257,
                latitude: 28.046023,
                level: "Larger accidents",
                fmen: 34,
                reason: "Gas fires",
            },
            {
                index: 9,
                altitude: 100.448179,
                latitude: 28.118903,
                level: "Larger accidents",
                fmen: 36,
                reason: "Solid material fires",
            },
            {
                index: 10,
                altitude: 100.843344,
                latitude: 27.986194,
                level: "General Accidents",
                fmen: 12,
                reason: "Metal fires",
            },
            {
                index: 11,
                altitude: 102.741694,
                latitude: 27.734058,
                level: "General Accidents",
                fmen: 12,
                reason: "Gas fires",
            },
            {
                index: 12,
                altitude: 102.407076,
                latitude: 27.580634,
                level: "Major Accidents",
                fmen: 48,
                reason: "Solid material fires",
            },
            {
                index: 13,
                altitude: 102.430896,
                latitude: 27.909937,
                level: "General Accidents",
                fmen: 12,
                reason: "Liquid substance fire",
            },
            {
                index: 14,
                altitude: 102.420745,
                latitude: 28.474842,
                level: "General Accidents",
                fmen: 17,
                reason: "Gas fires",
            },
            {
                index: 15,
                altitude: 102.605023,
                latitude: 28.473936,
                level: "Larger accidents",
                fmen: 31,
                reason: "Metal fires",
            },
            {
                index: 16,
                altitude: 102.596312,
                latitude: 28.536853,
                level: "General Accidents",
                fmen: 15,
                reason: "Live fires",
            },
            {
                index: 17,
                altitude: 102.594016,
                latitude: 28.537001,
                level: "General Accidents",
                fmen: 23,
                reason: "Live fires",
            },
            {
                index: 18,
                altitude: 102.625965,
                latitude: 28.404426,
                level: "Major Accidents",
                fmen: 51,
                reason: "固体物质火灾",
            },
            {
                index: 19,
                altitude: 102.600842,
                latitude: 28.287857,
                level: "特别重大事故",
                fmen: 90,
                reason: "Metal fires",
            },
            {
                index: 20,
                altitude: 102.264636,
                latitude: 28.150179,
                level: "Major Accidents",
                fmen: 53,
                reason: "Live fires",
            },
        ],
    },
    getters: {},
    mutations: {},
    actions: {},
    modules: {}
})